name: Bookbarn

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  bookbarn_build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: laravel
          MYSQL_USER: laraveluser
          MYSQL_PASSWORD: password
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
      
      - name: Install Dependencies
        run: composer install

      
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      
      - name: Install NPM Dependencies
        run: npm install
      
      - name: Build Assets
        run: npm run build
      
      - name: Create Database
        env:
          DB_HOST: localhost
          DB_USERNAME: root
          DB_PASSWORD: password
        run: |
          sudo servicectl restart mysqld
          mysql -u${{ env.DB_USERNAME }} -p${{ env.DB_PASSWORD }} -h${{ env.DB_HOST }} -e "CREATE DATABASE laravel"

      - name: Copy .env.example to .env
        run: cp .env.example .env

      - name: Set Application Key
        run: php artisan key:generate

      - name: Change Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Clear Config
        run: php artisan config:clear

      - name: Run Migrations
        env:
          DB_HOST: localhost
          DB_USERNAME: laraveluser
          DB_PASSWORD: password
          DB_DATABASE: laravel
        run: php artisan migrate --seed --force
